name: Build and publish Docker image

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Log in to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" |
          docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Determine version
        id: vars
        shell: pwsh
        run: |
          if ($env:GITHUB_REF -like "refs/tags/*") {
              # Extract version from tag
              $Version = $env:GITHUB_REF.Replace("refs/tags/", "")
              "VERSION=$Version" | Out-File -FilePath $env:GITHUB_OUTPUT -Append
              "TAGGED=true" | Out-File -FilePath $env:GITHUB_OUTPUT -Append
          } else {
              # Manual workflow_dispatch
              "VERSION=latest" | Out-File -FilePath $env:GITHUB_OUTPUT -Append
              "TAGGED=false" | Out-File -FilePath $env:GITHUB_OUTPUT -Append
          }

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v4
        with:
          install: true
          driver: docker-container

      # Always push to latest, but only put VERSION if TAGGED is true
      - name: Build and push with cache
        uses: docker/build-push-action@v7
        with:
          context: .
          push: true
          tags: ${{
            join(format('ghcr.io/{0}/{1}:latest',
              github.repository_owner,
              github.event.repository.name),
            steps.vars.outputs.TAGGED == 'true' && format('ghcr.io/{0}/{1}:{2}',
              github.repository_owner,
              github.event.repository.name,
              steps.vars.outputs.VERSION) || null) }}
          cache-from: type=registry,ref=ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:cache
          cache-to: type=registry,ref=ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:cache,mode=max
